name: Test - Delete User
on:
  pull_request:
    branches: [ main ]

jobs:
  test-delete-user:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'

      - name: Instalar dependências
        working-directory: javascript
        run: npm install

      - name: Executar teste de deleção de usuário
        working-directory: javascript
        run: npm run test:delete